[package]
name = "reflexive"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = "1"
serde_json = "1"
serde_urlencoded = "0"
log = "0.4"
mime = "0"
env_logger = "0"
clap = { version = "4", features = ["derive"] }
colored = "3"